project:
  type: website
  output-dir: docs
  
website:
  title: "SEGUID v2"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Available Software
        menu:
          - text: "<strong>seguid</strong> (JavaScript package)"
            url:  https://github.com/seguid/seguid-javascript/
          - text: "<strong>seguid</strong> (Python package)"
            url:  https://seguid-python.seguid.org
          - text: "<strong>seguid</strong> (R package)"
            url:  https://seguid-r.seguid.org
          - text: "<strong>seguid</strong> (Tcl script)"
            url:  https://github.com/seguid/seguid-tcl/
      - text: Live Demo
        menu:
          - text: "Demo: SEGUID Calculator"
            href: demo-seguid-calculator.html
          - text: "Demo: Python package <strong>seguid</strong>"
            href: demo-python.html
          - text: "Demo: R package <strong>seguid</strong>"
            href: demo-r.html
      - quality.qmd
      - publications.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/seguid/seguid.org/
        aria-label: GitHub
        
  search: 
    location: navbar
    type: overlay
    
  repo-url: https://github.com/seguid/seguid.org/
  repo-actions: [source, edit, issue]
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  