---
title: "Demo: Python package seguid"
format: html
filters:
  - pyodide
webr:
  show-startup-message: false
  autoload-packages: true
---

This is an online demo of the Python package **[seguid]** and the SEGUID v2
algorithm.  The below examples run an Python instance completely within
your web browser based on [Pyodide] and [WebAssembly].

To run the examples, click 'Run Code'. Feel free to edit any of them
as you prefer. Nothing you type or enter below leaves your web
browser.  See **[seguid]** for the details on these functions,
including what type of arguments they take.


Requirement: Run the following code-snippet once:

```{pyodide-python}
#| read-only: true
#| autorun: true
import micropip
await micropip.install("seguid")
from seguid import *
```

::: {.callout-warning}

_WARNING: In order for the code snippets to work, you must click 'Run
Code' on the above code snippet once._

:::


## Examples

### Linear, single-stranded DNA

```{pyodide-python}
lsseguid("GATTACA")
```

### Linear, double-stranded DNA

```{pyodide-python}
ldseguid("GATTACA", "TGTAATC")
```

### Staggered linear, double-stranded DNA

```{pyodide-python}
ldseguid("-ATTACA", "--TAATC")
```

### Circular, single-stranded DNA

```{pyodide-python}
csseguid("GATTACA")
```

### Circular, double-stranded DNA

```{pyodide-python}
cdseguid("GATTACA", "TGTAATC")
```

### Protein

```{pyodide-python}
lsseguid("QSALTQPASV", alphabet = "{protein}")
```


### Expanded epigenetic double-stranded DNA

```{pyodide-python}
ldseguid("TTGmGCAA", "TTGC1CAA", alphabet = "{DNA},m1,h2,f3,c4")
```


[seguid]: https://seguid-python.seguid.org/
[Pyodide]: https://pyodide.org/en/stable/
[WebAssembly]: https://webassembly.org/
